services:
  ruby:
    build:
      context: ..
      dockerfile: ruby/Dockerfile
      args:
        INSTALL_CLAUDE: ${INSTALL_CLAUDE:-1}
    ports:
      - "127.0.0.1:3010-3019:3000" # Rails/Puma default dev server
    extends:
      file: ../common/base.docker-compose.yml
      service: base
