"""devtool/hostsetup.py — one-time host setup (`run.py setup`), replacing the old standalone
setup.sh: git identity, the generated common/.zshrc, an optional CA certificate bundle,
captured proxy settings, and the `dev` shell function in ~/.zshrc.
"""
import os
import subprocess
from pathlib import Path

from .docker_utils import REPO_ROOT, die


def _step(msg):
    print(f"\n▶ {msg}")


def _ok(msg):
    print(f"✅ {msg}")


def _info(msg):
    print(f"   {msg}")


def _git_config_get(key):
    r = subprocess.run(["git", "config", "--global", key], capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 else ""


def _setup_git_identity():
    _step("Git identity")
    cur_name = _git_config_get("user.name")
    cur_email = _git_config_get("user.email")

    name = input(f"  Name  [{cur_name or 'not set'}]: ").strip()
    email = input(f"  Email [{cur_email or 'not set'}]: ").strip()

    name = name or cur_name
    email = email or cur_email

    if name:
        subprocess.run(["git", "config", "--global", "user.name", name])
    if email:
        subprocess.run(["git", "config", "--global", "user.email", email])
    _ok(f"Git identity: {name} <{email}>")
    return name, email


# ---------------------------------------------------------------------------
# common/.zshrc — generated from the checked-in template so the real name/
# email never ends up in a commit. Regenerated every run; never git-add this
# file (see .gitignore).
# ---------------------------------------------------------------------------
def _setup_zshrc(name, email):
    _step("Container shell config (common/.zshrc)")
    template = REPO_ROOT / "common" / "zshrc-template"
    out = REPO_ROOT / "common" / ".zshrc"

    if name and email:
        text = template.read_text()
        text = text.replace("CHANGE_ME@example.com", email).replace("Change Me", name)
        out.write_text(text)
        _ok("common/.zshrc generated with your git identity.")
    else:
        out.write_text(template.read_text())
        _info("No name/email set — common/.zshrc generated with placeholder identity.")


def _setup_ca_bundle():
    _step("CA certificate bundle")
    certs_dir = REPO_ROOT / "common" / "scripts" / "certs"

    bundle = input("  Path to certificate bundle (leave empty to skip): ").strip()
    if not bundle:
        _info("Skipped. Drop .crt files in common/scripts/certs/ manually if needed.")
        return

    src = Path(bundle)
    if not src.is_file():
        die(f"File not found: {bundle}")

    dest_name = src.name
    # Ensure .crt extension so update-ca-certificates picks it up
    if dest_name.endswith(".pem"):
        dest_name = dest_name[: -len(".pem")] + ".crt"
    elif not dest_name.endswith(".crt"):
        dest_name = dest_name + ".crt"

    dest = certs_dir / dest_name
    dest.write_bytes(src.read_bytes())
    _ok(f"Certificate bundle copied to {certs_dir}/{dest_name}")
    _info("It will be installed into containers on the next build.")


def _proxy_line(key, value):
    return f"{key}={value}\n" if value else f"# {key}=\n"


# ---------------------------------------------------------------------------
# Proxy — capture from current shell environment
# ---------------------------------------------------------------------------
def _setup_proxy_env():
    _step("Proxy")
    proxy_env_file = REPO_ROOT / "proxy.env"

    http_ = os.environ.get("HTTP_PROXY") or os.environ.get("http_proxy") or ""
    https_ = os.environ.get("HTTPS_PROXY") or os.environ.get("https_proxy") or ""
    no_proxy_ = os.environ.get("NO_PROXY") or os.environ.get("no_proxy") or ""

    content = (
        "# Proxy configuration — generated by `run.py setup`\n"
        "# Edit this file to change proxy settings, then rebuild your containers.\n"
        + _proxy_line("HTTP_PROXY", http_)
        + _proxy_line("HTTPS_PROXY", https_)
        + _proxy_line("NO_PROXY", no_proxy_)
        + _proxy_line("http_proxy", http_)
        + _proxy_line("https_proxy", https_)
        + _proxy_line("no_proxy", no_proxy_)
    )
    proxy_env_file.write_text(content)

    if http_ or https_:
        _ok(f"Proxy written to proxy.env (HTTP={http_} HTTPS={https_})")
    else:
        _ok("proxy.env written — no proxy variables were set in the current shell.")
        _info("Edit proxy.env and uncomment the relevant lines if you need a proxy.")


# ---------------------------------------------------------------------------
# `dev` command — add shell function to ~/.zshrc
# ---------------------------------------------------------------------------
def _setup_dev_function():
    _step("'dev' command")
    zshrc = Path.home() / ".zshrc"
    marker = "# devcontainer dev()"

    existing = zshrc.read_text() if zshrc.exists() else ""
    if marker in existing:
        _info(f"dev() already present in {zshrc} — skipping.")
        return

    run_py = REPO_ROOT / "run.py"
    block = f'\n{marker}\ndev() {{ "{run_py}" -v "$(pwd)" "$@"; }}\n'
    with zshrc.open("a") as fh:
        fh.write(block)
    _ok(f"dev() added to {zshrc}")
    _info("Run 'source ~/.zshrc' or open a new shell to activate it.")


def run():
    name, email = _setup_git_identity()
    _setup_zshrc(name, email)
    _setup_ca_bundle()
    _setup_proxy_env()
    _setup_dev_function()

    print("\n🎉 Setup complete. Open any project with:\n")
    print("   cd /path/to/your/project")
    print("   dev\n")
