#!/bin/sh
# setup.sh — One-time host setup for devcontainers.
# Configures git identity, imports a certificate bundle, captures proxy
# settings from the current shell, and adds the `dev` command to ~/.zshrc.

set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

die()  { echo "❌ ERROR: $*" >&2; exit 1; }
ok()   { echo "✅ $*"; }
info() { echo "   $*"; }
step() { printf "\n▶ %s\n" "$*"; }

# ---------------------------------------------------------------------------
# Git identity
# ---------------------------------------------------------------------------
step "Git identity"

_cur_name="$(git config --global user.name  2>/dev/null || true)"
_cur_email="$(git config --global user.email 2>/dev/null || true)"

printf "  Name  [%s]: " "${_cur_name:-not set}"
read -r _name
printf "  Email [%s]: " "${_cur_email:-not set}"
read -r _email

_name="${_name:-${_cur_name}}"
_email="${_email:-${_cur_email}}"

[ -n "$_name" ]  && git config --global user.name  "$_name"
[ -n "$_email" ] && git config --global user.email "$_email"
ok "Git identity: ${_name} <${_email}>"

# ---------------------------------------------------------------------------
# common/.zshrc — generated from the checked-in template so the real name/
# email never ends up in a commit. Regenerated every run; never git-add this
# file (see .gitignore).
# ---------------------------------------------------------------------------
step "Container shell config (common/.zshrc)"

ZSHRC_TEMPLATE="$SCRIPT_DIR/common/zshrc-template"
ZSHRC_OUT="$SCRIPT_DIR/common/.zshrc"

if [ -n "$_name" ] && [ -n "$_email" ]; then
    _escape_sed() { printf '%s' "$1" | sed -e 's/[&|]/\\&/g'; }
    sed \
        -e "s|CHANGE_ME@example.com|$(_escape_sed "$_email")|" \
        -e "s|Change Me|$(_escape_sed "$_name")|" \
        "$ZSHRC_TEMPLATE" > "$ZSHRC_OUT"
    ok "common/.zshrc generated with your git identity."
else
    cp "$ZSHRC_TEMPLATE" "$ZSHRC_OUT"
    info "No name/email set — common/.zshrc generated with placeholder identity."
fi

# ---------------------------------------------------------------------------
# CA certificate bundle
# ---------------------------------------------------------------------------
step "CA certificate bundle"

CERTS_DIR="$SCRIPT_DIR/common/scripts/certs"

printf "  Path to certificate bundle (leave empty to skip): "
read -r _bundle

if [ -n "$_bundle" ]; then
    [ -f "$_bundle" ] || die "File not found: $_bundle"
    _dest="$CERTS_DIR/$(basename "$_bundle")"
    # Ensure .crt extension so update-ca-certificates picks it up
    case "$_dest" in
        *.crt) ;;
        *.pem) _dest="${_dest%.pem}.crt" ;;
        *)     _dest="${_dest}.crt" ;;
    esac
    cp "$_bundle" "$_dest"
    ok "Certificate bundle copied to $CERTS_DIR/$(basename "$_dest")"
    info "It will be installed into containers on the next build."
else
    info "Skipped. Drop .crt files in common/scripts/certs/ manually if needed."
fi

# ---------------------------------------------------------------------------
# Proxy — capture from current shell environment
# ---------------------------------------------------------------------------
step "Proxy"

PROXY_ENV="$SCRIPT_DIR/proxy.env"

_http="${HTTP_PROXY:-${http_proxy:-}}"
_https="${HTTPS_PROXY:-${https_proxy:-}}"
_noproxy="${NO_PROXY:-${no_proxy:-}}"

_line() {
    _k="$1" _v="$2"
    if [ -n "$_v" ]; then printf '%s=%s\n' "$_k" "$_v"
    else                   printf '# %s=\n'  "$_k"
    fi
}

cat > "$PROXY_ENV" << EOF
# Proxy configuration — generated by setup.sh
# Edit this file to change proxy settings, then rebuild your containers.
$(_line HTTP_PROXY  "$_http")
$(_line HTTPS_PROXY "$_https")
$(_line NO_PROXY    "$_noproxy")
$(_line http_proxy  "$_http")
$(_line https_proxy "$_https")
$(_line no_proxy    "$_noproxy")
EOF

if [ -n "$_http" ] || [ -n "$_https" ]; then
    ok "Proxy written to proxy.env (HTTP=$_http HTTPS=$_https)"
else
    ok "proxy.env written — no proxy variables were set in the current shell."
    info "Edit proxy.env and uncomment the relevant lines if you need a proxy."
fi

# ---------------------------------------------------------------------------
# Egress-proxy — regenerate squid.conf (chains through the corporate proxy
# above if one was detected, otherwise egresses directly) and (re)start the
# shared proxy stack so devcontainers can join it.
# ---------------------------------------------------------------------------
step "Egress-proxy (common/egress-proxy)"

EGRESS_DIR="$SCRIPT_DIR/common/egress-proxy"
SQUID_TEMPLATE="$EGRESS_DIR/squid.conf.template"
SQUID_CONF="$EGRESS_DIR/squid.conf"

_upstream="${_https:-$_http}"
if [ -n "$_upstream" ]; then
    _hostport="${_upstream#*://}"
    _hostport="${_hostport#*@}"
    _hostport="${_hostport%%/*}"
    _peer_host="${_hostport%%:*}"
    _peer_port="${_hostport##*:}"
    [ "$_peer_host" != "$_peer_port" ] || _peer_port=80
    _cache_peer_line="cache_peer ${_peer_host} parent ${_peer_port} 0 no-query default"
else
    _cache_peer_line="# no corporate proxy detected — egressing directly"
fi

awk -v line="$_cache_peer_line" '{ gsub(/# __CACHE_PEER__/, line); print }' \
    "$SQUID_TEMPLATE" > "$SQUID_CONF"

if command -v docker >/dev/null 2>&1; then
    ( cd "$EGRESS_DIR" && docker compose up -d --build ) \
        && ok "egress-proxy running (allowlist: common/egress-proxy/allowlist.txt)" \
        || info "Could not (re)start egress-proxy — start it manually later if needed."
else
    info "docker not found — skipped starting egress-proxy. Run it later with:"
    info "  ( cd common/egress-proxy && docker compose up -d --build )"
fi

# ---------------------------------------------------------------------------
# `dev` command — add shell function to ~/.zshrc
# ---------------------------------------------------------------------------
step "'dev' command"

_zshrc="$HOME/.zshrc"
_marker="# devcontainer dev()"

if grep -qF "$_marker" "$_zshrc" 2>/dev/null; then
    info "dev() already present in $_zshrc — skipping."
else
    cat >> "$_zshrc" << EOF

$_marker
dev() { "$SCRIPT_DIR/run.sh" -v "\$(pwd)" "\$@"; }
EOF
    ok "dev() added to $_zshrc"
    info "Run 'source ~/.zshrc' or open a new shell to activate it."
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
printf "\n🎉 Setup complete. Open any project with:\n\n"
printf "   cd /path/to/your/project\n"
printf "   dev\n\n"
