services:
  java:
    extends:
      file: ../common/base.docker-compose.yml
      service: base
    build:
      context: ..
      dockerfile: ./java/Dockerfile
      args:
        INSTALL_CLAUDE: ${INSTALL_CLAUDE:-1}
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
        NO_PROXY: ${NO_PROXY:-}
        http_proxy: ${http_proxy:-}
        https_proxy: ${https_proxy:-}
        no_proxy: ${no_proxy:-}
        JAVA_VERSION: ${JAVA_VERSION:-}
      secrets:
        - github_token
    ports:
      - "127.0.0.1:8080-8089:8080" # Spring Boot default dev server
      - "127.0.0.1:5005-5014:5005" # JDWP default debug port
    volumes:
      - ~/.m2:/home/ubuntu/.m2

secrets:
  github_token:
    environment: "GITHUB_TOKEN"
