services:
  rust:
    extends:
      file: ../common/base.docker-compose.yml
      service: base
    build:
      context: ..
      dockerfile: ./rust/Dockerfile
      args:
        INSTALL_CLAUDE: ${INSTALL_CLAUDE:-0}
