services:
  opentofu:
    build:
      context: ..
      dockerfile: opentofu/Dockerfile
      args:
        INSTALL_CLAUDE: ${INSTALL_CLAUDE:-0}
    extends:
      file: ../common/base.docker-compose.yml
      service: base
    volumes:
      - ./.zshrc2:/home/ubuntu/.zshrc2
