services:
  opentofu:
    build:
      context: ..
      dockerfile: opentofu/Dockerfile
      args:
        AGENTS: ${AGENTS:-}
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
        NO_PROXY: ${NO_PROXY:-}
        http_proxy: ${http_proxy:-}
        https_proxy: ${https_proxy:-}
        no_proxy: ${no_proxy:-}
      secrets:
        - github_token
    extends:
      file: ../common/base.docker-compose.yml
      service: base
    volumes:
      - ./.zshrc2:/home/ubuntu/.zshrc2

secrets:
  github_token:
    environment: "GITHUB_TOKEN"
