services:
  uv:
    build:
      context: ..
      dockerfile: ./uv/Dockerfile
      args:
        INSTALL_CLAUDE: ${INSTALL_CLAUDE:-0}
    extends:
      file: ../common/base.docker-compose.yml
      service: base
    ports:
      - "127.0.0.1:8010-8019:8000" # Django default dev server
    volumes:
      - ./.zshrc2:/home/ubuntu/.zshrc2
