services:
  uv:
    build:
      context: ..
      dockerfile: ./uv/Dockerfile
      args:
        INSTALL_CLAUDE: ${INSTALL_CLAUDE:-1}
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
        NO_PROXY: ${NO_PROXY:-}
        http_proxy: ${http_proxy:-}
        https_proxy: ${https_proxy:-}
        no_proxy: ${no_proxy:-}
    extends:
      file: ../common/base.docker-compose.yml
      service: base
    ports:
      - "127.0.0.1:8010-8019:8000" # Django default dev server
    volumes:
      - ./.zshrc2:/home/ubuntu/.zshrc2
