services:
  iac:
    build:
      context: ..
      dockerfile: iac/Dockerfile
      args:
        AGENTS: ${AGENTS:-}
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
        NO_PROXY: ${NO_PROXY:-}
        http_proxy: ${http_proxy:-}
        https_proxy: ${https_proxy:-}
        no_proxy: ${no_proxy:-}
      secrets:
        - github_token
    extends:
      file: ../common/base.docker-compose.yml
      service: base
    network_mode: host
    volumes:
      - ./.zshrc2:/home/ubuntu/.zshrc2
      - ~/.aws/:/home/ubuntu/.aws
      - ~/.azure:/home/ubuntu/.azure
      - ~/.terraform.d:/home/ubuntu/.terraform.d
      - ~/.spacelift:/home/ubuntu/.spacelift

secrets:
  github_token:
    environment: "GITHUB_TOKEN"
