services:
  web:
    extends:
      file: ../common/base.docker-compose.yml
      service: base
    build:
      context: ..
      dockerfile: ./web/Dockerfile
      args:
        AGENTS: ${AGENTS:-}
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
        NO_PROXY: ${NO_PROXY:-}
        http_proxy: ${http_proxy:-}
        https_proxy: ${https_proxy:-}
        no_proxy: ${no_proxy:-}
      secrets:
        - github_token
    ports:
      - "127.0.0.1:3000-3009:3000" # Node/Express default dev server
      - "127.0.0.1:5173-5182:5173" # Vite default dev server

secrets:
  github_token:
    environment: "GITHUB_TOKEN"
